baseURL = 'https://swkwien.github.io/gdcr21hugo/'
languageCode = 'en-us'
title = 'Global Day of Coderetreat 2021 by swkWien at Nagarro'

theme = "reveal-hugo"

custom_css = ["css/custom.css"]  # only works in theory, see all related changes: TODOCSS

[author]
name = "TODO add facilitators"

[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true
